### ISSUE TITLE
Rename as integrate.simpson using newer version of scipy

### ISSUE THREAD

**Issue by kluophysics** [ru-ccmt/eDMFT#7]
It looks like that in `src/exactDC/CmpSlaterInt.py`, the old scipy.integrate.simps is not working with new version of scipy.
I'm suggesting to use the scipy.integrate.simpson instead in case anyone encounters the same problem!

**Comment by haulek** [comment]
Has been corrected recently.

**Comment by kluophysics** [comment]
> Has been corrected recently.

Thanks a lot! I will close it.
